name: 'Trunk Based Release Versioning'
description: 'Release versioning based on the trunk based development branching model, Cloned from Fredrik Arvidsson action repository [https://github.com/actions-marketplace-validations/Fresa_trunk-based-release-versioning/blob/main/action.yml]'
outputs:
  version:
    description: 'Release version in SemVer format'
    value: ${{ steps.calc-version.outputs.version }}
  major-version:
    description: 'The major version'
    value: ${{ steps.calc-version.outputs.major-version }}
  minor-version:
    description: 'The minor version'
    value: ${{ steps.calc-version.outputs.minor-version }}
  patch-version:
    description: 'The patch version'
    value: ${{ steps.calc-version.outputs.patch-version }}
  is-prerelease:
    description: 'Is this a prerelease?'
    value: ${{ steps.calc-version.outputs.is-prerelease }}
  commit-count:
    description: 'Number of commits the release consists off'
    value: ${{ steps.calc-version.outputs.commit-count }}
  commit-logs-path:
    description: >-
      The path to the file containing the commit logs for the release.
      The logs are formatted as yaml in the format of 'hash: %H%nmessage: | %n %s%n%n %b%n---'.
    value: ${{ steps.calc-version.outputs.commit-logs-path }}
  release-ref:
    description: 'The commit SHA to the release'
    value: ${{ steps.calc-version.outputs.release-ref }}
  last-release-ref:
    description: 'The commit SHA to the last release'
    value: ${{ steps.calc-version.outputs.last-release-ref }}
runs:
  using: 'composite'
  steps:
  - id: calc-version
    run: |
      . "${GITHUB_ACTION_PATH}/scripts/next_release.sh"
      echo "version=$TBV_VERSION" >> $GITHUB_OUTPUT
      echo "is-prerelease=$TBV_IS_PRERELEASE" >> $GITHUB_OUTPUT
      echo "major-version=$TBV_MAJOR_VERSION" >> $GITHUB_OUTPUT
      echo "minor-version=$TBV_MINOR_VERSION" >> $GITHUB_OUTPUT
      echo "patch-version=$TBV_PATCH_VERSION" >> $GITHUB_OUTPUT
      echo "commit-count=$TBV_COMMIT_COUNT" >> $GITHUB_OUTPUT
      echo "commit-logs-path=$TBV_COMMIT_LOGS_PATH" >> $GITHUB_OUTPUT
      echo "release-ref=$TBV_RELEASE_REF" >> $GITHUB_OUTPUT
      echo "last-release-ref=$TBV_LAST_RELEASE_REF" >> $GITHUB_OUTPUT
    shell: bash
branding:
  icon: 'tag'
  color: 'orange'
